apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: the-container
        image: hseligson/kustomize-sample-app:v1.0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: MY_MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: mysqlDB
